import { useState, useEffect, useRef } from 'react';
import { FileText, X, Download, Copy, Check } from 'lucide-react';
import './style.css';
import TranscriptionEntry from '../transcriptionEntry/transcriptionEntry';


const TranscriptionWidget = ({ 
  isOpen, 
  setIsOpen, 
  entries,
  meetingId,
  userId 
}) => {
  const [displayEntries, setDisplayEntries] = useState([]);
  const [copied, setCopied] = useState(false);
  const messagesEndRef = useRef(null);
  const containerRef = useRef(null);

  // Scroll to bottom of transcriptions
  const scrollToBottom = (smooth = true) => {
    if (messagesEndRef.current) {
      messagesEndRef.current.scrollIntoView({
        behavior: smooth ? 'smooth' : 'auto',
        block: 'end',
      });
    }
  };

  // Load complete history when widget opens
  useEffect(() => {
    if (isOpen) {
      setDisplayEntries(entries);
      // Scroll to bottom after a short delay to ensure rendering
      setTimeout(() => scrollToBottom(false), 100);
    }
  }, [isOpen, entries]);

  // Auto-scroll when new entries arrive (only if widget is open)
  useEffect(() => {
    if (isOpen && displayEntries.length > 0) {
      scrollToBottom();
    }
  }, [displayEntries.length, isOpen]);

  // Copy all transcription text
  const handleCopyAll = () => {
    const text = entries
      .map(e => {
        const minutes = Math.floor(e.secondsIntoMeeting / 60);
        const seconds = e.secondsIntoMeeting % 60;
        const timeStr = `${minutes}:${seconds.toString().padStart(2, '0')}`;
        return `[${timeStr}] ${e.userName}: ${e.text}`;
      })
      .join('\n');

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Export as text file
  const handleExport = () => {
    const text = `Meeting Transcript
Meeting ID: ${meetingId}
Date: ${new Date().toLocaleString()}
Total Entries: ${entries.length}

${entries
  .map(e => {
    const minutes = Math.floor(e.secondsIntoMeeting / 60);
    const seconds = e.secondsIntoMeeting % 60;
    const timeStr = `${minutes}:${seconds.toString().padStart(2, '0')}`;
    return `[${timeStr}] ${e.userName}: ${e.text}`;
  })
  .join('\n')}

---
Generated by MyMeet
`;

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `transcript-${meetingId}-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className={`transcription-widget ${isOpen ? 'open' : 'closed'}`}>
      {/* Header */}
      <div className="transcription-header">
        <div className="header-left">
          <FileText size={20} />
          <h3>Live Transcription</h3>
        </div>
        <div className="header-actions">
          <button 
            onClick={handleCopyAll} 
            className="header-action-btn"
            title={copied ? 'Copied!' : 'Copy all'}
            disabled={entries.length === 0}
          >
            {copied ? <Check size={16} /> : <Copy size={16} />}
          </button>
          <button 
            onClick={handleExport} 
            className="header-action-btn"
            title="Export as text file"
            disabled={entries.length === 0}
          >
            <Download size={16} />
          </button>
          <button 
            onClick={() => setIsOpen(false)} 
            className="close-btn"
            title="Close transcription"
          >
            <X size={20} />
          </button>
        </div>
      </div>

      {/* Transcription Body */}
      <div className="transcription-body" ref={containerRef}>
        {displayEntries.length === 0 ? (
          <div className="transcription-empty">
            <FileText size={48} />
            <p>No transcriptions yet</p>
            <span>Speech will be transcribed automatically</span>
          </div>
        ) : (
          <div className="transcription-list">
            {displayEntries.map((entry) => (
              <TranscriptionEntry
                key={entry.id}
                entry={entry}
                isOwnEntry={entry.userId === userId}
              />
            ))}
            <div ref={messagesEndRef} />
          </div>
        )}
      </div>

      {/* Footer with info */}
      <div className="transcription-footer">
        <div className="transcription-info">
          <span className="info-item">
            <FileText size={12} />
            {entries.length} {entries.length === 1 ? 'entry' : 'entries'}
          </span>
          <span className="info-separator">•</span>
          <span className="info-item">Auto-transcribing</span>
        </div>
      </div>
    </div>
  );
};

export default TranscriptionWidget;