import { useState, useEffect, useRef } from 'react';
import { FileText, X, Download, Copy, Check } from 'lucide-react';
import './style.css';
import TranscriptionEntry from '../transcriptionEntry/transcriptionEntry';

const TranscriptionWidget = ({ 
  isOpen, 
  setIsOpen, 
  entries,
  interimTranscriptions, // Map<userId, {text, userName, lastUpdate}>
  meetingId,
  userId 
}) => {
  const [copied, setCopied] = useState(false);
  const messagesEndRef = useRef(null);
  const containerRef = useRef(null);
  const [displayMode, setDisplayMode] = useState('live'); // 'live' or 'final-only'

  // Scroll to bottom
  const scrollToBottom = (smooth = true) => {
    if (messagesEndRef.current) {
      messagesEndRef.current.scrollIntoView({
        behavior: smooth ? 'smooth' : 'auto',
        block: 'end',
      });
    }
  };

  // Scroll when entries or interim updates change
  useEffect(() => {
    if (isOpen) {
      scrollToBottom();
    }
  }, [entries.length, interimTranscriptions?.size, isOpen]);

  // Initial scroll when widget opens
  useEffect(() => {
    if (isOpen) {
      setTimeout(() => scrollToBottom(false), 100);
    }
  }, [isOpen]);

  // Copy all transcription text (final only)
  const handleCopyAll = () => {
    const text = entries
      .map(e => {
        const minutes = Math.floor(e.secondsIntoMeeting / 60);
        const seconds = e.secondsIntoMeeting % 60;
        const timeStr = `${minutes}:${seconds.toString().padStart(2, '0')}`;
        return `[${timeStr}] ${e.userName}: ${e.text}`;
      })
      .join('\n');

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Export as text file (final only)
  const handleExport = () => {
    const text = `Meeting Transcript
Meeting ID: ${meetingId}
Date: ${new Date().toLocaleString()}
Total Entries: ${entries.length}

${entries
  .map(e => {
    const minutes = Math.floor(e.secondsIntoMeeting / 60);
    const seconds = e.secondsIntoMeeting % 60;
    const timeStr = `${minutes}:${seconds.toString().padStart(2, '0')}`;
    return `[${timeStr}] ${e.userName}: ${e.text}`;
  })
  .join('\n')}

---
Generated by MyMeet
`;

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `transcript-${meetingId}-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const hasContent = entries.length > 0 || (interimTranscriptions && interimTranscriptions.size > 0);

  return (
    <div className={`transcription-widget ${isOpen ? 'open' : 'closed'}`}>
      {/* Header */}
      <div className="transcription-header">
        <div className="header-left">
          <FileText size={20} />
          <h3>Live Transcription</h3>
        </div>
        <div className="header-actions">
          <button 
            onClick={handleCopyAll} 
            className="header-action-btn"
            title={copied ? 'Copied!' : 'Copy all'}
            disabled={entries.length === 0}
          >
            {copied ? <Check size={16} /> : <Copy size={16} />}
          </button>
          <button 
            onClick={handleExport} 
            className="header-action-btn"
            title="Export as text file"
            disabled={entries.length === 0}
          >
            <Download size={16} />
          </button>
          <button 
            onClick={() => setIsOpen(false)} 
            className="close-btn"
            title="Close transcription"
          >
            <X size={20} />
          </button>
        </div>
      </div>

      {/* Transcription Body */}
      <div className="transcription-body" ref={containerRef}>
        {!hasContent ? (
          <div className="transcription-empty">
            <FileText size={48} />
            <p>No transcriptions yet</p>
            <span>Speech will be transcribed automatically</span>
          </div>
        ) : (
          <div className="transcription-list">
            {/* Render final entries */}
            {entries.map((entry) => (
              <TranscriptionEntry
                key={entry.id}
                entry={entry}
                isOwnEntry={entry.userId === userId}
              />
            ))}

            {/* Render interim transcriptions (typing effect) */}
            {interimTranscriptions && interimTranscriptions.size > 0 && (
              <>
                {Array.from(interimTranscriptions.values()).map((interim) => (
                  <div 
                    key={`interim-${interim.userId}`}
                    className={`transcription-entry interim ${interim.userId === userId ? 'own' : 'other'}`}
                  >
                    <div className="entry-header">
                      <span className="entry-user">{interim.userName}:</span>
                      <span className="entry-interim-badge">typing...</span>
                    </div>
                    <div className="entry-text interim-text">
                      {interim.text}
                      <span className="typing-cursor">|</span>
                    </div>
                  </div>
                ))}
              </>
            )}

            <div ref={messagesEndRef} />
          </div>
        )}
      </div>

      {/* Footer with info */}
      <div className="transcription-footer">
        <div className="transcription-info">
          <span className="info-item">
            <FileText size={12} />
            {entries.length} {entries.length === 1 ? 'entry' : 'entries'}
          </span>
          <span className="info-separator">•</span>
          <span className="info-item">
            {interimTranscriptions && interimTranscriptions.size > 0 ? (
              <>
                <span className="pulse-dot"></span>
                Live transcribing
              </>
            ) : (
              'Auto-transcribing'
            )}
          </span>
        </div>
      </div>
    </div>
  );
};

export default TranscriptionWidget;